#:kivy 2.1.0



<Test>:
    canvas.before:
        Color:
            rgb: 1,1,1
        Rectangle:
            pos: self.pos
            size: self.size
            
    orientation: 'vertical'
    Label:
        canvas.before:
            Color:
                rgba: 0,0,0, 0.5
            Rectangle:
                pos: self.pos
                size: self.size    
        text:"Bienvenue dans le menu de test"
        size_hint: 1, 0.1    
        font_size: '30sp'
        color: 1, 1, 1, 1
    Button:
        pos_hint:{'center_x':0.5, 'center_y':0.5}
        canvas.before:
            Color:
                rgb: 1,1,1
            Rectangle:
                pos: self.pos
                size: self.size
        text: "Ajouer un Etudiant"
        size_hint: 1, 0.1
        font_size: '20sp'
        on_press: app.gestion.transition.direction='left';app.gestion.current='ajoutEtudiant'